apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: matrix-system

resources:
- namespace.yaml
- deployment.yaml
- service.yaml

commonLabels:
  app.kubernetes.io/name: matrix-update-server
  app.kubernetes.io/part-of: matrix-system